### ISSUE TITLE
TypeError: setCheckState on src/main.py

### ISSUE THREAD

**Issue by dekacypher** [StephanAkkerman/Live_Binance_Charts#6]
I get this error when running the main.py file. I've tried reading the documentation and experimenting, but with no progress.

I use python 3.11.1
PyQt6 (the older version isn't working for me)

`No settings found, using default
Traceback (most recent call last):
  File "/Users/dekahalane/Documents/GitHub/Live_Binance_Charts/src/main.py", line 824, in <module>
    control_panel = create_ctrl_panel()
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/dekahalane/Documents/GitHub/Live_Binance_Charts/src/main.py", line 668, in create_ctrl_panel
    panel.USDTmode.setCheckState(0)
TypeError: setCheckState(self, Qt.CheckState): argument 1 has unexpected type 'int'`

**Comment by StephanAkkerman** [comment]
Thanks for letting me know, I will rewrite this program once I have the time for it. It looks like they updated the libraries something in create_ctrl_panel broke because of that.

**Comment by StephanAkkerman** [comment]
@dekacypher I was bored, so I fixed the code, everything should work with PyQt6 now
